#! /bin/bash

DIR="$HOME/.devsync/"

download () {
  URL="$1"
  TARGET="$2"

  cd $DIR
    wget --quiet -O $TARGET $URL
    chmod +x $TARGET
  cd - > /dev/null
}

link () {
  TARGET="$1"
  ALIAS="$2"

  ln -s $( which $TARGET ) ~/.devsync/$ALIAS
}

mkdir -p $DIR

heroku plugins:install https://github.com/leonkenneth/devsync-heroku-plugin.git
download "https://s3.amazonaws.com/leonkenneth/devsync/$OSTYPE/devsync-init" "devsync-init"
download "https://s3.amazonaws.com/leonkenneth/devsync/$OSTYPE/devsync-watch" "devsync-watch"

echo "*"
echo "You are all set! Go to an Heroku app directory and type \`heroku dev:init\` to get started"
